name = "DistDir"
uuid = "7dc8f0b9-4771-4d8f-b1d2-8a6f5f760eb4"
authors = ["Enrico Degregori"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
