name = "DistDir"
uuid = "7dc8f0b9-4771-4d8f-b1d2-8a6f5f760eb4"
authors = ["Enrico Degregori"]
version = "1.0.0-DEV"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
